### ISSUE TITLE
log_alpha picture in Readme

### ISSUE THREAD

**Issue by hjzzju** [mangushev/aligntts#2]
Thanks for the amazing implementation. I am wondering if this picture is the result of training phase 0.

**Comment by mangushev** [comment]
Hi, I cannot say now 100% but I am pretty confident. You probably know the paper. So this hidden markov models approach helps to figure out Gaussian parameters which represents characters. So we see which character each Mel spectrogram belongs to. And we are maximizing joint log probability to get the best alignment. So when in phase 0, mixed density network is trained, it gives us good alignment, we also run other algorithm to cleanup this since we also have some rules due to sequence of mels and characters. These pictures should be close as in readme. In the later phase, fft and mixed density are jointly trained, but it does not much change the alignment. It is possible that somehow joint training is mishandled, then you will observe that nice picture is destroyed, not nice any more! Basically, you have trained network and you can always check the picture if it is still looks good!
